<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>_0923_WpfApp1</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TextTemplate1.tt" />
    <None Remove="TextTemplate1.txt" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Readme.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Readme.MD</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Readme.md">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Readme.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
